jobs:
  uaa_standalone_test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: liberica
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: ./gradlew --no-daemon -Dspring.profiles.active=default,hsqldb -DfailOnPassedAfterRetry=false
        --no-daemon test
    strategy:
      fail-fast: false
      matrix:
        java:
        - '17'
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
permissions:
  contents: read
