jobs:
  labeler:
    name: Label the PR size
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        fail_if_xl: 'false'
        files_to_ignore: ''
        github_api_url: api.github.com
        l_label: size/l
        l_max_size: '1000'
        m_label: size/m
        m_max_size: '500'
        message_if_xl: 'This PR exceeds the recommended size of 1000 lines. Please
          make sure you are NOT addressing multiple issues with one PR. Note this
          PR might be rejected due to its size.

          '
        s_label: size/s
        s_max_size: '100'
        xl_label: size/xl
        xs_label: size/xs
        xs_max_size: '10'
name: labeler
on:
  repository_dispatch:
    types: trigger-ga___labeler.yml
