jobs:
  Sonar-Test-Analysis:
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: liberica
        java-version: '17'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: env.SONAR_TOKEN != ''
      name: Analyze with SonarCloud
      run: ./gradlew --no-daemon -Dspring.profiles.active=default,hsqldb -DfailOnPassedAfterRetry=false
        --no-daemon test jacocoTestReport || true; ./gradlew --no-daemon sonar; ./gradlew
        --no-daemon jacocoTestReport;
name: SonarCloud analysis
on:
  repository_dispatch:
    types: trigger-ga___sonarcloud.yml
permissions:
  pull-requests: read
